// @mostajs/init — Code generator
// Author: Dr Hamid MADANI drmdh@msn.com
import fs from 'fs'
import path from 'path'
import type { ModuleInfo, CodegenOptions } from '../types/index.js'

/**
 * Generate DAL registry code that registers all schemas from installed modules.
 *
 * @example Output:
 * ```ts
 * import { registerSchemas } from '@mostajs/orm';
 * import { UserSchema, RoleSchema } from '@mostajs/auth';
 * import { TicketSchema, ScanLogSchema } from '@mostajs/ticketing';
 * registerSchemas([UserSchema, RoleSchema, TicketSchema, ScanLogSchema]);
 * ```
 */
export function generateRegistry(modules: ModuleInfo[]): string {
  const lines: string[] = [
    '// Entity Registry — Auto-generated by @mostajs/init',
    '// Register project schemas into MostaORM',
    "import { registerSchemas } from '@mostajs/orm';",
    '',
  ]

  const allSchemas: string[] = []

  for (const mod of modules) {
    if (!mod.installed || mod.capabilities.schemaNames.length === 0) continue
    const schemas = mod.capabilities.schemaNames
    lines.push(`import { ${schemas.join(', ')} } from '${mod.name}';`)
    allSchemas.push(...schemas)
  }

  if (allSchemas.length > 0) {
    lines.push('')
    lines.push(`registerSchemas([`)
    for (const s of allSchemas) {
      lines.push(`  ${s},`)
    }
    lines.push(`]);`)
  }

  lines.push('')
  return lines.join('\n')
}

/**
 * Generate DAL service code with repository factory functions.
 *
 * @example Output:
 * ```ts
 * import { getDialect } from '@mostajs/orm';
 * import { UserRepository } from '@mostajs/auth';
 * export async function userRepo() { return new UserRepository(await getDialect()); }
 * ```
 */
export function generateDalService(modules: ModuleInfo[]): string {
  const lines: string[] = [
    '// DAL Service — Auto-generated by @mostajs/init',
    '// Centralized repository access',
    "import { getDialect } from '@mostajs/orm';",
    "import './registry';",
    '',
  ]

  const factories: string[] = []

  for (const mod of modules) {
    if (!mod.installed || mod.capabilities.repositoryNames.length === 0) continue
    const repos = mod.capabilities.repositoryNames
    lines.push(`import { ${repos.join(', ')} } from '${mod.name}';`)

    for (const repo of repos) {
      const fnName = repoToFunctionName(repo)
      factories.push(
        `export async function ${fnName}() { return new ${repo}(await getDialect()); }`
      )
    }
  }

  if (factories.length > 0) {
    lines.push('')
    lines.push(...factories)
  }

  lines.push('')
  return lines.join('\n')
}

/**
 * Generate an API route file for a route factory.
 *
 * @example Output:
 * ```ts
 * import { createTicketsHandler } from '@mostajs/ticketing/api/tickets.route';
 * import { ticketRepo, clientRepo } from '@/dal/service';
 * import { checkPermission } from '@/lib/authCheck';
 * export const { GET, POST } = createTicketsHandler({ ... });
 * ```
 */
export function generateRouteStub(
  factoryName: string,
  moduleName: string,
  factoryImportPath: string,
): string {
  const methods = factoryName.toLowerCase().includes('scan') ? '{ POST }' : '{ GET, POST }'

  return `// Auto-generated by @mostajs/init
import { ${factoryName} } from '${factoryImportPath}';
// TODO: Import your DAL repositories from '@/dal/service'
// TODO: Import your auth check from '@/lib/authCheck'

export const ${methods} = ${factoryName}({
  checkAuth: async (req) => {
    // TODO: Implement auth check
    return { error: null, userId: '' }
  },
  getRepositories: async () => ({
    // TODO: Provide required repositories
  }),
})
`
}

/**
 * Apply codegen: write generated files to the project.
 * Returns list of files written.
 */
export function applyCodegen(
  modules: ModuleInfo[],
  options: CodegenOptions,
): { written: string[]; skipped: string[] } {
  const { projectRoot, srcDir = 'src' } = options
  const written: string[] = []
  const skipped: string[] = []

  // Generate registry
  const registryPath = path.join(projectRoot, options.dalRegistryPath || `${srcDir}/dal/registry.ts`)
  if (!fs.existsSync(registryPath)) {
    const registryCode = generateRegistry(modules)
    ensureDir(path.dirname(registryPath))
    fs.writeFileSync(registryPath, registryCode, 'utf-8')
    written.push(registryPath)
  } else {
    skipped.push(registryPath + ' (already exists)')
  }

  // Generate DAL service
  const servicePath = path.join(projectRoot, options.dalServicePath || `${srcDir}/dal/service.ts`)
  if (!fs.existsSync(servicePath)) {
    const serviceCode = generateDalService(modules)
    ensureDir(path.dirname(servicePath))
    fs.writeFileSync(servicePath, serviceCode, 'utf-8')
    written.push(servicePath)
  } else {
    skipped.push(servicePath + ' (already exists)')
  }

  // Generate route stubs for each route factory
  for (const mod of modules) {
    if (!mod.installed) continue
    for (const factory of mod.capabilities.routeFactories) {
      const routeName = factoryToRoutePath(factory)
      const routePath = path.join(projectRoot, srcDir, 'app', 'api', routeName, 'route.ts')
      if (!fs.existsSync(routePath)) {
        const routeExport = mod.exports.find(
          (e) => e.subpath.includes('api') || e.subpath.includes('route')
        )
        const importPath = routeExport?.importPath || mod.name
        const code = generateRouteStub(factory, mod.name, importPath)
        ensureDir(path.dirname(routePath))
        fs.writeFileSync(routePath, code, 'utf-8')
        written.push(routePath)
      } else {
        skipped.push(routePath + ' (already exists)')
      }
    }
  }

  return { written, skipped }
}

/** Convert 'UserRepository' to 'userRepo' */
function repoToFunctionName(repoClass: string): string {
  const base = repoClass.replace(/Repository$/, '')
  return base.charAt(0).toLowerCase() + base.slice(1) + 'Repo'
}

/** Convert factory name to route path */
function factoryToRoutePath(factoryName: string): string {
  return factoryName
    .replace(/^create/, '')
    .replace(/Handler$/, '')
    .replace(/([A-Z])/g, '-$1')
    .toLowerCase()
    .replace(/^-/, '')
}

function ensureDir(dir: string) {
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true })
  }
}
