// @mostajs/init — CRUD page & form generator
// Author: Dr Hamid MADANI drmdh@msn.com
//
// Generates complete CRUD pages from @mostajs/orm EntitySchema:
// - List page (table with search, pagination, actions)
// - Create/Edit form page
// - API routes (GET list, POST create, PUT update, DELETE)

// ── Types ────────────────────────────────────────────────────

interface FieldInfo {
  name: string
  type: string
  required: boolean
  unique: boolean
  enum?: string[]
  label: string
}

interface RelationInfo {
  name: string
  target: string
  type: string
  label: string
}

interface CrudConfig {
  entityName: string
  collection: string
  fields: FieldInfo[]
  relations: RelationInfo[]
  timestamps: boolean
  /** Base route path, e.g. '/dashboard/clients' */
  basePath: string
  /** API base, e.g. '/api/clients' */
  apiPath: string
  /** Permission prefix, e.g. 'client' */
  permissionPrefix: string
}

export interface CrudOutput {
  listPage: { path: string; code: string }
  formPage: { path: string; code: string }
  apiRoute: { path: string; code: string }
  apiIdRoute: { path: string; code: string }
}

// ── Helpers ──────────────────────────────────────────────────

function fieldToLabel(name: string): string {
  return name
    .replace(/([A-Z])/g, ' $1')
    .replace(/^./, (c) => c.toUpperCase())
    .trim()
}

function fieldToInputType(type: string): string {
  switch (type) {
    case 'number': return 'number'
    case 'boolean': return 'checkbox'
    case 'date': return 'date'
    default: return 'text'
  }
}

// ── Public API ───────────────────────────────────────────────

/**
 * Generate CRUD config from a raw EntitySchema object.
 */
export function entityToCrudConfig(
  schema: { name: string; collection: string; fields: Record<string, any>; relations: Record<string, any>; timestamps: boolean },
  basePath?: string,
  apiPath?: string,
): CrudConfig {
  const fields: FieldInfo[] = Object.entries(schema.fields).map(([name, def]) => ({
    name,
    type: def.type || 'string',
    required: !!def.required,
    unique: !!def.unique,
    enum: def.enum,
    label: fieldToLabel(name),
  }))

  const relations: RelationInfo[] = Object.entries(schema.relations).map(([name, def]: [string, any]) => ({
    name,
    target: def.target,
    type: def.type || 'many-to-one',
    label: fieldToLabel(name),
  }))

  const slug = schema.collection || schema.name.toLowerCase() + 's'
  return {
    entityName: schema.name,
    collection: slug,
    fields,
    relations,
    timestamps: schema.timestamps,
    basePath: basePath || `/dashboard/${slug}`,
    apiPath: apiPath || `/api/${slug}`,
    permissionPrefix: schema.name.toLowerCase(),
  }
}

/**
 * Generate all CRUD files from a CrudConfig.
 */
export function generateCrud(config: CrudConfig): CrudOutput {
  return {
    listPage: {
      path: `src/app${config.basePath}/page.tsx`,
      code: generateListPage(config),
    },
    formPage: {
      path: `src/app${config.basePath}/[id]/page.tsx`,
      code: generateFormPage(config),
    },
    apiRoute: {
      path: `src/app${config.apiPath}/route.ts`,
      code: generateApiRoute(config),
    },
    apiIdRoute: {
      path: `src/app${config.apiPath}/[id]/route.ts`,
      code: generateApiIdRoute(config),
    },
  }
}

// ── List Page Generator ──────────────────────────────────────

function generateListPage(c: CrudConfig): string {
  const displayFields = c.fields.filter((f) => !['json', 'array'].includes(f.type)).slice(0, 6)

  return `// Generated by @mostajs/init — ${c.entityName} list page
'use client'

import { useState, useEffect, useCallback } from 'react'
import { Card, CardContent, CardHeader, CardTitle } from '@mostajs/ui/card'
import { Button } from '@mostajs/ui/button'
import { Input } from '@mostajs/ui/input'
import { Badge } from '@mostajs/ui/badge'
import { Table, TableHeader, TableBody, TableRow, TableHead, TableCell } from '@mostajs/ui/table'
import { Plus, Search, Edit, Trash2 } from 'lucide-react'
import Link from 'next/link'

interface ${c.entityName} {
  id: string
${c.fields.map((f) => `  ${f.name}: ${f.type === 'number' ? 'number' : f.type === 'boolean' ? 'boolean' : f.type === 'date' ? 'string' : 'string'}`).join('\n')}
}

export default function ${c.entityName}ListPage() {
  const [items, setItems] = useState<${c.entityName}[]>([])
  const [search, setSearch] = useState('')
  const [loading, setLoading] = useState(true)

  const fetchItems = useCallback(async () => {
    setLoading(true)
    try {
      const params = search ? \`?search=\${encodeURIComponent(search)}\` : ''
      const res = await fetch(\`${c.apiPath}\${params}\`)
      if (res.ok) {
        const json = await res.json()
        setItems(json.data || [])
      }
    } finally {
      setLoading(false)
    }
  }, [search])

  useEffect(() => { fetchItems() }, [fetchItems])

  const handleDelete = async (id: string) => {
    if (!confirm('Confirmer la suppression ?')) return
    await fetch(\`${c.apiPath}/\${id}\`, { method: 'DELETE' })
    fetchItems()
  }

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <h1 className="text-2xl font-bold text-gray-900">${c.entityName}s</h1>
        <Link href="${c.basePath}/new">
          <Button><Plus className="mr-2 h-4 w-4" /> Nouveau</Button>
        </Link>
      </div>

      <Card>
        <CardHeader>
          <div className="flex items-center gap-4">
            <div className="relative flex-1">
              <Search className="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-gray-400" />
              <Input
                placeholder="Rechercher..."
                value={search}
                onChange={(e) => setSearch(e.target.value)}
                className="pl-10"
              />
            </div>
          </div>
        </CardHeader>
        <CardContent>
          <Table>
            <TableHeader>
              <TableRow>
${displayFields.map((f) => `                <TableHead>${f.label}</TableHead>`).join('\n')}
                <TableHead className="w-24">Actions</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {items.map((item) => (
                <TableRow key={item.id}>
${displayFields.map((f) => {
    if (f.enum) return `                  <TableCell><Badge>{item.${f.name}}</Badge></TableCell>`
    if (f.type === 'boolean') return `                  <TableCell>{item.${f.name} ? 'Oui' : 'Non'}</TableCell>`
    if (f.type === 'date') return `                  <TableCell>{new Date(item.${f.name}).toLocaleDateString()}</TableCell>`
    return `                  <TableCell>{item.${f.name}}</TableCell>`
  }).join('\n')}
                  <TableCell>
                    <div className="flex gap-1">
                      <Link href={\`${c.basePath}/\${item.id}\`}>
                        <Button variant="ghost" size="icon"><Edit className="h-4 w-4" /></Button>
                      </Link>
                      <Button variant="ghost" size="icon" onClick={() => handleDelete(item.id)}>
                        <Trash2 className="h-4 w-4 text-red-500" />
                      </Button>
                    </div>
                  </TableCell>
                </TableRow>
              ))}
              {items.length === 0 && !loading && (
                <TableRow>
                  <TableCell colSpan={${displayFields.length + 1}} className="text-center text-gray-400 py-8">
                    Aucun element
                  </TableCell>
                </TableRow>
              )}
            </TableBody>
          </Table>
        </CardContent>
      </Card>
    </div>
  )
}
`
}

// ── Form Page Generator ──────────────────────────────────────

function generateFormPage(c: CrudConfig): string {
  const editableFields = c.fields.filter((f) => !['createdAt', 'updatedAt'].includes(f.name))

  return `// Generated by @mostajs/init — ${c.entityName} create/edit form
'use client'

import { useState, useEffect } from 'react'
import { useRouter, useParams } from 'next/navigation'
import { Card, CardContent, CardHeader, CardTitle } from '@mostajs/ui/card'
import { Button } from '@mostajs/ui/button'
import { Input } from '@mostajs/ui/input'
import { Label } from '@mostajs/ui/label'
${c.fields.some((f) => f.enum) ? "import { Select, SelectTrigger, SelectValue, SelectContent, SelectItem } from '@mostajs/ui/select'" : ''}
${c.fields.some((f) => f.type === 'boolean') ? "import { Checkbox } from '@mostajs/ui/checkbox'" : ''}
import { Save, ArrowLeft } from 'lucide-react'
import Link from 'next/link'

export default function ${c.entityName}FormPage() {
  const router = useRouter()
  const params = useParams()
  const isEdit = params.id !== 'new'

  const [form, setForm] = useState({
${editableFields.map((f) => {
    const def = f.type === 'number' ? '0' : f.type === 'boolean' ? 'false' : "''"
    return `    ${f.name}: ${def},`
  }).join('\n')}
  })
  const [saving, setSaving] = useState(false)

  useEffect(() => {
    if (isEdit) {
      fetch(\`${c.apiPath}/\${params.id}\`)
        .then((r) => r.json())
        .then((json) => { if (json.data) setForm(json.data) })
    }
  }, [isEdit, params.id])

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault()
    setSaving(true)
    try {
      const url = isEdit ? \`${c.apiPath}/\${params.id}\` : '${c.apiPath}'
      const method = isEdit ? 'PUT' : 'POST'
      const res = await fetch(url, {
        method,
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(form),
      })
      if (res.ok) router.push('${c.basePath}')
    } finally {
      setSaving(false)
    }
  }

  const set = (field: string, value: unknown) => setForm((prev) => ({ ...prev, [field]: value }))

  return (
    <div className="space-y-6">
      <div className="flex items-center gap-4">
        <Link href="${c.basePath}">
          <Button variant="ghost" size="icon"><ArrowLeft className="h-4 w-4" /></Button>
        </Link>
        <h1 className="text-2xl font-bold text-gray-900">
          {isEdit ? 'Modifier' : 'Nouveau'} ${c.entityName}
        </h1>
      </div>

      <Card>
        <CardContent className="pt-6">
          <form onSubmit={handleSubmit} className="space-y-4 max-w-xl">
${editableFields.map((f) => {
    if (f.enum) {
      return `            <div>
              <Label>${f.label}${f.required ? ' *' : ''}</Label>
              <Select value={String(form.${f.name})} onValueChange={(v) => set('${f.name}', v)}>
                <SelectTrigger><SelectValue placeholder="Selectionner" /></SelectTrigger>
                <SelectContent>
${f.enum.map((v) => `                  <SelectItem value="${v}">${v}</SelectItem>`).join('\n')}
                </SelectContent>
              </Select>
            </div>`
    }
    if (f.type === 'boolean') {
      return `            <div className="flex items-center gap-2">
              <Checkbox checked={!!form.${f.name}} onCheckedChange={(v) => set('${f.name}', v)} />
              <Label>${f.label}</Label>
            </div>`
    }
    return `            <div>
              <Label>${f.label}${f.required ? ' *' : ''}</Label>
              <Input
                type="${fieldToInputType(f.type)}"
                value={form.${f.name} ?? ''}
                onChange={(e) => set('${f.name}', ${f.type === 'number' ? 'Number(e.target.value)' : 'e.target.value'})}
                ${f.required ? 'required' : ''}
              />
            </div>`
  }).join('\n')}

            <div className="flex gap-2 pt-4">
              <Button type="submit" disabled={saving}>
                <Save className="mr-2 h-4 w-4" />
                {saving ? 'Enregistrement...' : 'Enregistrer'}
              </Button>
              <Link href="${c.basePath}">
                <Button type="button" variant="outline">Annuler</Button>
              </Link>
            </div>
          </form>
        </CardContent>
      </Card>
    </div>
  )
}
`
}

// ── API Route Generator ──────────────────────────────────────

function generateApiRoute(c: CrudConfig): string {
  const repoFn = c.entityName.charAt(0).toLowerCase() + c.entityName.slice(1) + 'Repo'

  return `// Generated by @mostajs/init — ${c.entityName} API route
import { ${repoFn} } from '@/dal/service'
import { checkPermission } from '@/lib/authCheck'

export async function GET(req: Request) {
  const { error } = await checkPermission('${c.permissionPrefix}:view')
  if (error) return error

  const repo = await ${repoFn}()
  const url = new URL(req.url)
  const search = url.searchParams.get('search') || ''

  let data
  if (search) {
    data = await repo.search(search)
  } else {
    data = await repo.findAll({}, { sort: { createdAt: -1 } })
  }

  return Response.json({ data })
}

export async function POST(req: Request) {
  const { error, session } = await checkPermission('${c.permissionPrefix}:create')
  if (error) return error

  const body = await req.json()
  const repo = await ${repoFn}()
  const created = await repo.create(body)

  return Response.json({ data: created }, { status: 201 })
}
`
}

function generateApiIdRoute(c: CrudConfig): string {
  const repoFn = c.entityName.charAt(0).toLowerCase() + c.entityName.slice(1) + 'Repo'

  return `// Generated by @mostajs/init — ${c.entityName} [id] API route
import { ${repoFn} } from '@/dal/service'
import { checkPermission } from '@/lib/authCheck'
import { NextRequest } from 'next/server'

export async function GET(req: NextRequest, { params }: { params: Promise<{ id: string }> }) {
  const { error } = await checkPermission('${c.permissionPrefix}:view')
  if (error) return error

  const { id } = await params
  const repo = await ${repoFn}()
  const item = await repo.findById(id)
  if (!item) return Response.json({ error: { message: 'Not found' } }, { status: 404 })

  return Response.json({ data: item })
}

export async function PUT(req: NextRequest, { params }: { params: Promise<{ id: string }> }) {
  const { error } = await checkPermission('${c.permissionPrefix}:edit')
  if (error) return error

  const { id } = await params
  const body = await req.json()
  const repo = await ${repoFn}()
  const updated = await repo.update(id, body)
  if (!updated) return Response.json({ error: { message: 'Not found' } }, { status: 404 })

  return Response.json({ data: updated })
}

export async function DELETE(req: NextRequest, { params }: { params: Promise<{ id: string }> }) {
  const { error } = await checkPermission('${c.permissionPrefix}:delete')
  if (error) return error

  const { id } = await params
  const repo = await ${repoFn}()
  await repo.delete(id)

  return Response.json({ data: { ok: true } })
}
`
}
